version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:latest"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
 
 #Mosquitto
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      # This port is for Webhooks
      - "9001:9001"
    volumes:
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
      
# do termostatów      
      
  bt-mqtt-gateway:
    image: zewelor/bt-mqtt-gateway
    container_name: bt-mqtt-gateway
    privileged: true
    restart: always
    volumes:
      - /opt/bt-mqtt-gateway/config.yaml:/application/config.yaml
      
    command: /bin/bash -c "hciconfig hci0 reset"   

    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host 
    
    
    
  #VSCode
  vscode:
    container_name: vscode
    image: codercom/code-server
    volumes:
      # Set <project dir> to the directory you want to open in VS Code.
      - /opt/vscode/config:/config
      # <vs code config> should point to a local dir where vs code stores its data.
      - /opt:/home/coder/.local/share/code-server
    ports:
      - "8443:8080"
    command: code-server --auth none --disable-telemetry /config
    restart: unless-stopped      

#ESPHome 
  esphome:
    container_name: esphome
    image: esphome/esphome
    ports:
      - "6052:6052"
    volumes:
      # Update PATH_TO_YOUR_CONFIG, the :rw gives the container Read/Write access
      - /opt/esphome/config:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    # You do have to map a serial port here. Determine your port and uncomment.
    #devices:
    #  - /dev/ttyAMC0:/dev/ttyAMC0
    restart: always
    
#Zigbee2MQTT
  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    image: koenkk/zigbee2mqtt
    volumes:
      - /opt/zigbee2mqtt/data:/app/data
      - /run/zigbee2mqtt/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 100M
    restart: always
    privileged: true
    
  rtl433:
    build:
      context: /opt/rtl2hassio
   
    container_name: rtl433
    devices:
      - /dev/bus/usb
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC: "RTL_433"
      MQTT_USERNAME: ""
      MQTT_PASSWORD: ""
      MQTT_RETAIN: "true"
      PROTOCOL: "-R 12 -R 19 -R 30 -R 35"
      DISCOVERY_PREFIX: "homeassistant"
      DISCOVERY_INTERVAL: 30
      BLACK_LIST: ""
    depends_on:
      - mosquitto
    links:
      - mosquitto   


